@startuml
'https://plantuml.com/class-diagram


hide method

class User
{
    * id : long
    name : varchar
}

class Recipe
{
    * id : long
    + owner_id : long
    + name : varchar
    + instructions : varchar
    servings : int
}

class Ingredient
{
    * id : long
    + name : varchar
    description : varchar
    unit : varchar
    vegetarian : boolean
}


Recipe::owner_user_id -u-> User::id


class Recipe_Ingredient_Rel {
    * id : long
    + recipe_id : long
    + ingredient_id : long
    quantity : decimal
}

Recipe::id <-u- Recipe_Ingredient_Rel::recipe_id
Ingredient::id <-u- Recipe_Ingredient_Rel::product_id


@enduml