@startuml
'https://plantuml.com/class-diagram


hide method

class User as "ApplicationUser" << (S,#3388FF) >>
{
    * id : varchar
    username : varchar
    password : varchar
}

note top of User
 This ApplicationUser entity
 is intended as a placeholder
 for the company IAM system
end note

class Recipe << (E,#008800) >>
{
    * id : long
    + owner_id : long
    + name : varchar
    instructions : varchar
    servings : int
}

class Ingredient << (E,#008800) >>
{
    * id : long
    + name : varchar
    description : varchar
    unit : varchar
    vegetarian : boolean
}


Recipe::owner_id -u-> User::id


class RecipeIngredientRelation  << (R,#00CC00) >>
 {
    * id : long
    + recipe_id : long
    + ingredient_id : long
    quantity : decimal
}

note top of RecipeIngredientRelation
 This RecipeIngredientRelation entity
 connect the Recipe with the Ingredient,
 creating the N-M relation between
 the two entities, and enabling
 the storage of the relation dependent
 info quantity
end note


Recipe::id <-u- RecipeIngredientRelation::recipe_id
Ingredient::id <-u- RecipeIngredientRelation::product_id


@enduml